export const nigerianInstructors = [
  {
    id: 1,
    firstName: "Chukwuemeka",
    lastName: "Okafor",
    email: "chukwuemeka.okafor@univaciti.com",
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    bio: "Senior Cloud Architect with 12 years experience at MTN Nigeria and Microsoft. AWS Solutions Architect Professional certified.",
    specialization: "cloud-engineering",
    role: "instructor" as const,
  },
  {
    id: 2,
    firstName: "Ngozi",
    lastName: "Adeyemi",
    email: "ngozi.adeyemi@univaciti.com",
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    bio: "Data Science Lead at Flutterwave. Former Google Developer Expert. PhD in Computer Science from University of Lagos.",
    specialization: "data-analytics",
    role: "instructor" as const,
  },
  {
    id: 3,
    firstName: "Oluwaseun",
    lastName: "Afolabi",
    email: "oluwaseun.afolabi@univaciti.com",
    avatar: "https://randomuser.me/api/portraits/men/67.jpg",
    bio: "Principal Software Engineer at Paystack. 10+ years Java/Spring experience. Oracle Certified Professional.",
    specialization: "software-java",
    role: "instructor" as const,
  },
  {
    id: 4,
    firstName: "Adaeze",
    lastName: "Nwachukwu",
    email: "adaeze.nwachukwu@univaciti.com",
    avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    bio: "Frontend Architect at Kuda Bank. React contributor and conference speaker. Andela alumni.",
    specialization: "software-react",
    role: "instructor" as const,
  },
  {
    id: 5,
    firstName: "Babatunde",
    lastName: "Ogundimu",
    email: "babatunde.ogundimu@univaciti.com",
    avatar: "https://randomuser.me/api/portraits/men/52.jpg",
    bio: "QA Director at Interswitch. ISTQB certified. 15 years in software testing and quality assurance.",
    specialization: "quality-assurance",
    role: "instructor" as const,
  },
  {
    id: 6,
    firstName: "Folake",
    lastName: "Balogun",
    email: "folake.balogun@univaciti.com",
    avatar: "https://randomuser.me/api/portraits/women/33.jpg",
    bio: "Solutions Architect at AWS Nigeria. Previously at Dangote Group IT. Multi-cloud certified.",
    specialization: "solutions-architecture",
    role: "instructor" as const,
  },
  {
    id: 7,
    firstName: "Ikechukwu",
    lastName: "Eze",
    email: "ikechukwu.eze@univaciti.com",
    avatar: "https://randomuser.me/api/portraits/men/22.jpg",
    bio: "AI Research Lead at Data Science Nigeria. PhD from MIT. Published researcher in NLP and computer vision.",
    specialization: "ai-ml",
    role: "instructor" as const,
  },
];

export const nigerianStudents = [
  { id: 101, firstName: "Adaobi", lastName: "Okeke", points: 2450, coursesCompleted: 5, streak: 21 },
  { id: 102, firstName: "Emeka", lastName: "Nnamdi", points: 2380, coursesCompleted: 4, streak: 18 },
  { id: 103, firstName: "Funmilayo", lastName: "Adebayo", points: 2290, coursesCompleted: 5, streak: 30 },
  { id: 104, firstName: "Gbenga", lastName: "Oluwole", points: 2150, coursesCompleted: 4, streak: 14 },
  { id: 105, firstName: "Halima", lastName: "Yusuf", points: 2080, coursesCompleted: 3, streak: 25 },
  { id: 106, firstName: "Ifeanyi", lastName: "Ugochukwu", points: 1950, coursesCompleted: 4, streak: 12 },
  { id: 107, firstName: "Jumoke", lastName: "Fashola", points: 1890, coursesCompleted: 3, streak: 19 },
  { id: 108, firstName: "Kunle", lastName: "Ajayi", points: 1820, coursesCompleted: 3, streak: 16 },
  { id: 109, firstName: "Lola", lastName: "Bakare", points: 1750, coursesCompleted: 3, streak: 11 },
  { id: 110, firstName: "Musa", lastName: "Ibrahim", points: 1680, coursesCompleted: 2, streak: 22 },
  { id: 111, firstName: "Nneka", lastName: "Obi", points: 1620, coursesCompleted: 3, streak: 9 },
  { id: 112, firstName: "Obiora", lastName: "Chukwuma", points: 1550, coursesCompleted: 2, streak: 15 },
  { id: 113, firstName: "Patience", lastName: "Etuk", points: 1490, coursesCompleted: 2, streak: 8 },
  { id: 114, firstName: "Quadri", lastName: "Lawal", points: 1430, coursesCompleted: 2, streak: 13 },
  { id: 115, firstName: "Rashida", lastName: "Abdullahi", points: 1380, coursesCompleted: 2, streak: 7 },
];

export const mockCourses = [
  {
    id: 1,
    title: "AWS Cloud Engineering Masterclass",
    slug: "aws-cloud-engineering-masterclass",
    specialization: "cloud-engineering",
    description: "Master cloud computing with AWS. Learn to design, deploy, and manage scalable cloud infrastructure for Nigerian enterprises. Covers EC2, S3, Lambda, VPC, and more.",
    shortDescription: "Build expertise in AWS cloud services and infrastructure",
    technologies: ["aws", "docker", "kubernetes", "terraform", "linux"],
    difficulty: "intermediate",
    duration: 80,
    isPublished: true,
    isFeatured: true,
    instructor: nigerianInstructors[0],
    enrollmentCount: 1247,
    rating: 4.8,
    learningOutcomes: [
      "Design and deploy scalable AWS architectures",
      "Implement security best practices for cloud infrastructure",
      "Automate infrastructure using Terraform and CloudFormation",
      "Prepare for AWS Solutions Architect certification",
    ],
    modules: [
      { id: 1, title: "Cloud Computing Fundamentals", lessons: 8, duration: 120 },
      { id: 2, title: "AWS Core Services", lessons: 12, duration: 180 },
      { id: 3, title: "Networking & Security", lessons: 10, duration: 150 },
      { id: 4, title: "Serverless Architecture", lessons: 8, duration: 120 },
      { id: 5, title: "DevOps & CI/CD", lessons: 10, duration: 150 },
    ],
  },
  {
    id: 2,
    title: "Data Analytics with Python & Power BI",
    slug: "data-analytics-python-powerbi",
    specialization: "data-analytics",
    description: "Transform raw data into actionable business insights. Learn Python, SQL, and Power BI to analyze data for Nigerian banks, telecoms, and fintech companies.",
    shortDescription: "Master data analysis with Python, SQL, and Power BI",
    technologies: ["python", "postgresql", "powerbi", "pandas", "jupyter"],
    difficulty: "intermediate",
    duration: 60,
    isPublished: true,
    isFeatured: true,
    instructor: nigerianInstructors[1],
    enrollmentCount: 982,
    rating: 4.9,
    learningOutcomes: [
      "Analyze complex datasets using Python and Pandas",
      "Build interactive dashboards with Power BI",
      "Write efficient SQL queries for data extraction",
      "Apply statistical analysis to business problems",
    ],
    modules: [
      { id: 1, title: "Python for Data Analysis", lessons: 10, duration: 150 },
      { id: 2, title: "SQL & Database Querying", lessons: 8, duration: 120 },
      { id: 3, title: "Data Visualization with Power BI", lessons: 10, duration: 150 },
      { id: 4, title: "Statistical Analysis", lessons: 8, duration: 120 },
      { id: 5, title: "Capstone Project", lessons: 4, duration: 60 },
    ],
  },
  {
    id: 3,
    title: "Enterprise Java Development with Spring Boot",
    slug: "java-spring-boot-development",
    specialization: "software-java",
    description: "Become a professional Java developer. Master Spring Boot, microservices, and enterprise patterns used by Nigerian banks and fintech companies like Interswitch.",
    shortDescription: "Enterprise Java development with Spring Boot",
    technologies: ["java", "spring", "maven", "postgresql", "docker", "jenkins"],
    difficulty: "intermediate",
    duration: 100,
    isPublished: true,
    isFeatured: true,
    instructor: nigerianInstructors[2],
    enrollmentCount: 756,
    rating: 4.7,
    learningOutcomes: [
      "Build production-ready Spring Boot applications",
      "Design and implement microservices architecture",
      "Implement security with Spring Security and OAuth2",
      "Deploy applications with Docker and Kubernetes",
    ],
    modules: [
      { id: 1, title: "Java Fundamentals Refresher", lessons: 8, duration: 120 },
      { id: 2, title: "Spring Boot Deep Dive", lessons: 12, duration: 180 },
      { id: 3, title: "Microservices Architecture", lessons: 10, duration: 150 },
      { id: 4, title: "Security & Authentication", lessons: 8, duration: 120 },
      { id: 5, title: "Deployment & DevOps", lessons: 10, duration: 150 },
    ],
  },
  {
    id: 4,
    title: "Modern React Development",
    slug: "modern-react-development",
    specialization: "software-react",
    description: "Build modern web applications with React and TypeScript. Learn the tech stack used by Kuda, Piggyvest, and other Nigerian fintech startups.",
    shortDescription: "Modern frontend development with React & TypeScript",
    technologies: ["react", "typescript", "tailwindcss", "nodejs", "nextjs", "git"],
    difficulty: "intermediate",
    duration: 80,
    isPublished: true,
    isFeatured: true,
    instructor: nigerianInstructors[3],
    enrollmentCount: 1523,
    rating: 4.9,
    learningOutcomes: [
      "Build responsive React applications with TypeScript",
      "Implement state management with React Query and Zustand",
      "Create beautiful UIs with Tailwind CSS",
      "Deploy full-stack applications with Next.js",
    ],
    modules: [
      { id: 1, title: "React & TypeScript Fundamentals", lessons: 10, duration: 150 },
      { id: 2, title: "State Management Patterns", lessons: 8, duration: 120 },
      { id: 3, title: "Advanced React Patterns", lessons: 10, duration: 150 },
      { id: 4, title: "Full-Stack with Next.js", lessons: 10, duration: 150 },
      { id: 5, title: "Testing & Deployment", lessons: 8, duration: 120 },
    ],
  },
  {
    id: 5,
    title: "Quality Assurance Engineering",
    slug: "quality-assurance-engineering",
    specialization: "quality-assurance",
    description: "Master software testing and QA. Learn automation testing with Selenium, Cypress, and API testing. Prepare for QA roles at Nigerian tech companies.",
    shortDescription: "Automated testing and QA best practices",
    technologies: ["selenium", "jest", "cypress", "jenkins", "jira", "postman"],
    difficulty: "intermediate",
    duration: 60,
    isPublished: true,
    isFeatured: true,
    instructor: nigerianInstructors[4],
    enrollmentCount: 634,
    rating: 4.6,
    learningOutcomes: [
      "Design comprehensive test strategies",
      "Automate testing with Selenium and Cypress",
      "Perform API testing with Postman",
      "Integrate testing into CI/CD pipelines",
    ],
    modules: [
      { id: 1, title: "Testing Fundamentals", lessons: 8, duration: 120 },
      { id: 2, title: "Selenium WebDriver", lessons: 10, duration: 150 },
      { id: 3, title: "Cypress Modern Testing", lessons: 10, duration: 150 },
      { id: 4, title: "API & Performance Testing", lessons: 8, duration: 120 },
      { id: 5, title: "CI/CD Integration", lessons: 6, duration: 90 },
    ],
  },
  {
    id: 6,
    title: "Solutions Architecture Masterclass",
    slug: "solutions-architecture-masterclass",
    specialization: "solutions-architecture",
    description: "Design enterprise-grade solutions for African businesses. Learn system design, multi-cloud architecture, and patterns used by Dangote, Access Bank, and MTN.",
    shortDescription: "Enterprise architecture and system design",
    technologies: ["aws", "azure", "kubernetes", "microservices", "mongodb", "redis"],
    difficulty: "advanced",
    duration: 100,
    isPublished: true,
    isFeatured: true,
    instructor: nigerianInstructors[5],
    enrollmentCount: 445,
    rating: 4.8,
    learningOutcomes: [
      "Design scalable distributed systems",
      "Architect multi-cloud solutions",
      "Apply enterprise integration patterns",
      "Lead technical architecture decisions",
    ],
    modules: [
      { id: 1, title: "Architecture Fundamentals", lessons: 8, duration: 120 },
      { id: 2, title: "Distributed Systems Design", lessons: 12, duration: 180 },
      { id: 3, title: "Multi-Cloud Architecture", lessons: 10, duration: 150 },
      { id: 4, title: "Enterprise Patterns", lessons: 10, duration: 150 },
      { id: 5, title: "Case Studies & Capstone", lessons: 8, duration: 120 },
    ],
  },
  {
    id: 7,
    title: "AI & Machine Learning with Python",
    slug: "ai-machine-learning-python",
    specialization: "ai-ml",
    description: "Build intelligent applications with AI/ML. Learn TensorFlow, PyTorch, and deploy ML models. Apply AI to solve Nigerian business challenges.",
    shortDescription: "Build AI applications with Python and TensorFlow",
    technologies: ["python", "tensorflow", "pytorch", "jupyter", "opencv", "numpy"],
    difficulty: "advanced",
    duration: 120,
    isPublished: true,
    isFeatured: true,
    instructor: nigerianInstructors[6],
    enrollmentCount: 892,
    rating: 4.9,
    learningOutcomes: [
      "Build and train neural networks",
      "Implement computer vision applications",
      "Create NLP models for text analysis",
      "Deploy ML models to production",
    ],
    modules: [
      { id: 1, title: "ML Fundamentals & Python", lessons: 10, duration: 150 },
      { id: 2, title: "Deep Learning with TensorFlow", lessons: 12, duration: 180 },
      { id: 3, title: "Computer Vision", lessons: 10, duration: 150 },
      { id: 4, title: "Natural Language Processing", lessons: 10, duration: 150 },
      { id: 5, title: "ML in Production", lessons: 8, duration: 120 },
    ],
  },
];

export const mockEnrollments = [
  {
    id: 1,
    courseId: 4,
    course: mockCourses[3],
    progress: 65,
    currentModuleId: 3,
    currentLessonId: 2,
    enrolledAt: "2026-01-15T10:00:00Z",
    lastAccessedAt: "2026-02-03T09:30:00Z",
  },
  {
    id: 2,
    courseId: 2,
    course: mockCourses[1],
    progress: 42,
    currentModuleId: 2,
    currentLessonId: 4,
    enrolledAt: "2026-01-20T14:00:00Z",
    lastAccessedAt: "2026-02-02T16:45:00Z",
  },
  {
    id: 3,
    courseId: 1,
    course: mockCourses[0],
    progress: 25,
    currentModuleId: 1,
    currentLessonId: 6,
    enrolledAt: "2026-01-28T11:00:00Z",
    lastAccessedAt: "2026-02-01T20:15:00Z",
  },
];

export const allAchievements = [
  { id: 1, name: "First Steps", icon: "rocket", description: "Complete your first lesson", unlockCriteria: "Complete 1 lesson" },
  { id: 2, name: "Week Warrior", icon: "flame", description: "Maintain a 7-day learning streak", unlockCriteria: "7-day streak" },
  { id: 3, name: "Quiz Master", icon: "trophy", description: "Score 100% on any quiz", unlockCriteria: "Perfect quiz score" },
  { id: 4, name: "Course Champion", icon: "award", description: "Complete your first course", unlockCriteria: "Finish 1 course" },
  { id: 5, name: "Speed Learner", icon: "zap", description: "Complete 5 lessons in one day", unlockCriteria: "5 lessons in 24hrs" },
  { id: 6, name: "Night Owl", icon: "moon", description: "Study after 10 PM", unlockCriteria: "Learn after 10 PM" },
  { id: 7, name: "Early Bird", icon: "sunrise", description: "Study before 7 AM", unlockCriteria: "Learn before 7 AM" },
  { id: 8, name: "Dedicated", icon: "target", description: "Reach 30-day learning streak", unlockCriteria: "30-day streak" },
  { id: 9, name: "Expert", icon: "star", description: "Complete 5 courses", unlockCriteria: "Finish 5 courses" },
  { id: 10, name: "Certified Pro", icon: "badge", description: "Earn your first certification", unlockCriteria: "Pass certification exam" },
];

export const mockUserStats = {
  totalPoints: 1250,
  coursesCompleted: 2,
  coursesInProgress: 3,
  lessonsCompleted: 47,
  totalLessons: 120,
  currentStreak: 14,
  longestStreak: 21,
  totalTimeSpent: 4320,
  earnedBadgeIds: [1, 2, 3],
  rank: 23,
  totalStudents: 1523,
};

export const mockLeaderboard = nigerianStudents.map((student, index) => ({
  ...student,
  rank: index + 1,
  avatar: `https://randomuser.me/api/portraits/${index % 2 === 0 ? 'women' : 'men'}/${20 + index}.jpg`,
}));

export const techLogos: Record<string, string> = {
  aws: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original-wordmark.svg",
  azure: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/azure/azure-original.svg",
  googlecloud: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/googlecloud/googlecloud-original.svg",
  python: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg",
  java: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg",
  react: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg",
  docker: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg",
  kubernetes: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kubernetes/kubernetes-plain.svg",
  tensorflow: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tensorflow/tensorflow-original.svg",
  postgresql: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg",
  typescript: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg",
  javascript: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg",
  nodejs: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg",
  spring: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/spring/spring-original.svg",
  maven: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/maven/maven-original.svg",
  jenkins: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jenkins/jenkins-original.svg",
  git: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg",
  linux: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg",
  mongodb: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg",
  redis: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redis/redis-original.svg",
  terraform: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/terraform/terraform-original.svg",
  selenium: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/selenium/selenium-original.svg",
  jest: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jest/jest-plain.svg",
  cypress: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cypressio/cypressio-original.svg",
  jira: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jira/jira-original.svg",
  nextjs: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg",
  tailwindcss: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-original.svg",
  pytorch: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pytorch/pytorch-original.svg",
  jupyter: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jupyter/jupyter-original.svg",
  opencv: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/opencv/opencv-original.svg",
  numpy: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/numpy/numpy-original.svg",
  pandas: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pandas/pandas-original.svg",
  powerbi: "https://upload.wikimedia.org/wikipedia/commons/c/cf/New_Power_BI_Logo.svg",
  postman: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postman/postman-original.svg",
  microservices: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kubernetes/kubernetes-plain.svg",
};

export const specializationInfo: Record<string, { name: string; color: string; icon: string }> = {
  "cloud-engineering": { name: "Cloud Engineering", color: "#FF9900", icon: "cloud" },
  "data-analytics": { name: "Data Analytics", color: "#3366CC", icon: "chart" },
  "software-java": { name: "Java Development", color: "#ED8B00", icon: "code" },
  "software-react": { name: "React Development", color: "#61DAFB", icon: "code" },
  "quality-assurance": { name: "Quality Assurance", color: "#43B02A", icon: "check" },
  "solutions-architecture": { name: "Solutions Architecture", color: "#9B59B6", icon: "layers" },
  "ai-ml": { name: "AI & Machine Learning", color: "#FF6F00", icon: "brain" },
};

export const mockUsers = [
  { id: 1, username: "admin", email: "admin@univaciti.com", firstName: "Admin", lastName: "User", role: "admin", isActive: true, createdAt: "2025-01-01T10:00:00Z" },
  { id: 2, username: "instructor", email: "instructor@univaciti.com", firstName: "Sarah", lastName: "Johnson", role: "instructor", isActive: true, createdAt: "2025-01-02T10:00:00Z" },
  { id: 3, username: "chukwuemeka.okonkwo", email: "chukwuemeka@gmail.com", firstName: "Chukwuemeka", lastName: "Okonkwo", role: "student", isActive: true, createdAt: "2025-01-15T10:00:00Z" },
  { id: 4, username: "ngozi.adeyemi", email: "ngozi.adeyemi@yahoo.com", firstName: "Ngozi", lastName: "Adeyemi", role: "student", isActive: true, createdAt: "2025-01-16T10:00:00Z" },
  { id: 5, username: "oluwaseun.bakare", email: "seun.bakare@outlook.com", firstName: "Oluwaseun", lastName: "Bakare", role: "student", isActive: true, createdAt: "2025-01-17T10:00:00Z" },
  { id: 6, username: "amina.yusuf", email: "amina.yusuf@gmail.com", firstName: "Amina", lastName: "Yusuf", role: "student", isActive: true, createdAt: "2025-01-18T10:00:00Z" },
  { id: 7, username: "tunde.olatunji", email: "tunde.olatunji@gmail.com", firstName: "Tunde", lastName: "Olatunji", role: "student", isActive: true, createdAt: "2025-01-19T10:00:00Z" },
  { id: 8, username: "blessing.eze", email: "blessing.eze@yahoo.com", firstName: "Blessing", lastName: "Eze", role: "student", isActive: true, createdAt: "2025-01-20T10:00:00Z" },
  { id: 9, username: "ibrahim.musa", email: "ibrahim.musa@gmail.com", firstName: "Ibrahim", lastName: "Musa", role: "student", isActive: true, createdAt: "2025-01-21T10:00:00Z" },
  { id: 10, username: "folake.adeniyi", email: "folake.adeniyi@outlook.com", firstName: "Folake", lastName: "Adeniyi", role: "student", isActive: true, createdAt: "2025-01-22T10:00:00Z" },
  { id: 11, username: "emeka.nwachukwu", email: "emeka.nwachukwu@gmail.com", firstName: "Emeka", lastName: "Nwachukwu", role: "student", isActive: false, createdAt: "2025-01-23T10:00:00Z" },
  { id: 12, username: "aisha.abdullahi", email: "aisha.abdullahi@yahoo.com", firstName: "Aisha", lastName: "Abdullahi", role: "student", isActive: true, createdAt: "2025-01-24T10:00:00Z" },
];

export const mockAdminEnrollments = [
  { id: 1, userId: 3, courseId: 1, user: mockUsers[2], course: mockCourses[0], status: "active", progress: 65, enrolledAt: "2025-01-20T10:00:00Z" },
  { id: 2, userId: 4, courseId: 2, user: mockUsers[3], course: mockCourses[1], status: "completed", progress: 100, enrolledAt: "2025-01-21T10:00:00Z" },
  { id: 3, userId: 5, courseId: 3, user: mockUsers[4], course: mockCourses[2], status: "active", progress: 45, enrolledAt: "2025-01-22T10:00:00Z" },
  { id: 4, userId: 6, courseId: 1, user: mockUsers[5], course: mockCourses[0], status: "active", progress: 80, enrolledAt: "2025-01-23T10:00:00Z" },
  { id: 5, userId: 7, courseId: 4, user: mockUsers[6], course: mockCourses[3], status: "pending", progress: 0, enrolledAt: "2025-01-24T10:00:00Z" },
  { id: 6, userId: 8, courseId: 2, user: mockUsers[7], course: mockCourses[1], status: "active", progress: 30, enrolledAt: "2025-01-25T10:00:00Z" },
  { id: 7, userId: 9, courseId: 5, user: mockUsers[8], course: mockCourses[4], status: "completed", progress: 100, enrolledAt: "2025-01-26T10:00:00Z" },
  { id: 8, userId: 10, courseId: 1, user: mockUsers[9], course: mockCourses[0], status: "active", progress: 55, enrolledAt: "2025-01-27T10:00:00Z" },
  { id: 9, userId: 3, courseId: 6, user: mockUsers[2], course: mockCourses[5], status: "active", progress: 20, enrolledAt: "2025-01-28T10:00:00Z" },
  { id: 10, userId: 4, courseId: 7, user: mockUsers[3], course: mockCourses[6], status: "expired", progress: 15, enrolledAt: "2025-01-10T10:00:00Z" },
];
